version: "2"

services:

  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes_from:
      - data

  data:
    image: busybox:1
    volumes:
      - /var/lib/mysql:/var/lib/mysql